# Please consult conda-forge/core before doing this
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]

# for "no member named 'move' in namespace 'std'"
c_compiler_version:         # [osx and x86_64]
  - 10                      # [osx and x86_64]
cxx_compiler_version:       # [osx and x86_64]
  - 10                      # [osx and x86_64]
