{% set version = "0.4.1" %}

package:
  name: oxigraph
  version: {{ version }}

source:
  url: https://github.com/oxigraph/oxigraph/releases/download/v{{ version }}/oxigraph_v{{ version }}.tar.gz
  sha256: c7fe9f5946397eaf7c74408681a595ab8fbb49cd472ac7becc3082a1a74d5ba1

build:
  number: 0

outputs:
  - name: oxigraph-server
    build:
      script:
        - bash {{ RECIPE_DIR }}/build-oxigraph.sh        # [unix]
        - call {{ RECIPE_DIR }}\bld-oxigraph-server.bat  # [win]
    requirements:
      build:
        - libclang                  # [win]
        - llvm                      # [win]
        - llvm-tools                # [win]
        - clangdev                  # [not osx]
        - llvmdev                   # [not osx]
        - openssl                   # [build_platform != target_platform]
        - zstd                      # [build_platform != target_platform]
        - pkg-config                # [not (win or build_platform != target_platform)]
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("rust") }}
        - {{ stdlib("c") }}
        - cargo-bundle-licenses
      host:
        - rocksdb                   # [not (win or build_platform != target_platform)]
        - openssl
        - zstd
      run:
        - rocksdb                   # [not (win or build_platform != target_platform)]
        - ca-certificates
        - openssl
        - zstd
    test:
      commands:
        - oxigraph --version
        - oxigraph --help

  - name: pyoxigraph
    build:
      script:
        - bash {{ RECIPE_DIR }}/build-oxigraph.sh   # [unix]
        - call {{ RECIPE_DIR }}\bld-pyoxigraph.bat  # [win]
    requirements:
      build:
        - clangdev                            # [not osx]
        - llvmdev                             # [not osx]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - openssl                             # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
        - zstd                                # [build_platform != target_platform]
        - pkg-config                          # [not (win or build_platform != target_platform)]
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("rust") }}
        - {{ stdlib("c") }}
        - cargo-bundle-licenses
        - maturin >=1.0,<2.0
      host:
        - rocksdb                             # [not (win or build_platform != target_platform)]
        - maturin >=1.0,<2.0
        - openssl
        - pip
        - python
        - zstd
      run:
        - rocksdb                             # [not (win or build_platform != target_platform)]
        - ca-certificates
        - openssl
        - python
        - zstd
    test:
      files:
        - test_licenses.py
      source_files:
        - python/tests
      imports:
        - pyoxigraph
      commands:
        - pip check
        - cd python/tests
        - pytest -vv --color=yes --tb=long
        - mypy -p pyoxigraph
      requires:
        - mypy
        - pip
        - pytest

about:
  home: https://oxigraph.org
  summary: a SPARQL database and RDF toolkit
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

  dev_url: https://github.com/oxigraph/oxigraph
  doc_url: https://oxigraph.org

extra:
  feedstock-name: oxigraph
  recipe-maintainers:
    - Tpt
    - bollwyvl
